TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devkynctm3k.db
DATA += devkynctm3k.proto

#=======================================
include $(TOP)/configure/RULES
